name: 'ollama-open-webui'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    ports:
      - 11434:11434
    volumes:
      - ./ollama_data:/root/.ollama
      - ./ollama_entrypoint.sh:/entrypoint.sh
    environment:
      - 'OLLAMA_MAX_LOADED_MODELS=4'
      - 'OLLAMA_NUM_PARALLEL=1'
      - 'OLLAMA_KEEP_ALIVE=-1'
    entrypoint: ["/entrypoint.sh"]
    deploy:
      resources:
        limits:
          memory: 10G
    networks:
      - llm_net


  app:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: "app"
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - ollama
      - qdrant
    volumes:
      - ./backend:/app/backend
    networks:
      - llm_net

  front:
    build:
      context: .
      dockerfile: ./front/Dockerfile
    container_name: "front_app"
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8501:8501"
    depends_on:
      - ollama
      - qdrant
    volumes:
      - ./front:/app/front
    networks:
      - llm_net

  qdrant:
    container_name: "rag_personal_vector_db"
    restart: on-failure
    image: qdrant/qdrant:v1.13.3
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage:z
    networks:
      - llm_net

networks:
  llm_net:
    external: true
