embedding_model:
  model_name: nomic-embed-text:v1.5
  vector_size: 768

vector_repository:
  distance_type: cosine
  top_k: 5
  collection_name: documents

rag:
  system_prompt: |
    You are a helpful assistant that answers questions based on the provided context.
    If the answer is not in the context, say that you don't know instead of making up information.
    Use the following retrieved documents to answer the user's question:

llm_model:
  model_name: llama3.2:1b
  temperature: 0.2
  max_tokens: 2048
