from typing import List, Optional
from datetime import datetime, timezone
from pydantic import BaseModel, Field, ConfigDict

from src.components.rag.domain.value_objects import DocumentRetrieval


class Response(BaseModel):
    """A value object representing a response from a language model.

    This immutable object encapsulates the response content along with metadata
    about the generation process, including timing and token usage information.

    Attributes:
        content (str): The actual response text generated by the model.
        generated_at (datetime): UTC timestamp when the response was generated.
        model_used (str, optional): Name or identifier of the model that generated the response.
        processing_time_ms (int, optional): Time taken to generate the response in milliseconds.
        input_tokens (int, optional): Number of tokens in the input prompt.
        output_tokens (int, optional): Number of tokens in the generated response.
    """
    model_config = ConfigDict(frozen=True)

    content: str = Field(...)
    generated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    model_used: Optional[str] = Field(default=None)
    processing_time_ms: Optional[int] = Field(default=None)
    input_tokens: Optional[int] = Field(default=None)
    output_tokens: Optional[int] = Field(default=None)
    provider: Optional[str] = Field(default=None, description="The LLM provider used to generate the response")


class RAGResponse(Response):
    """RAG (Retrieval-Augmented Generation) response value object.

    This class extends the base Response class to include document sources
    that were retrieved and used during the RAG process.

    Attributes:
        sources (List[DocumentRetrieval]): List of documents that were retrieved
            and used as context for generating the response. Defaults to an empty list.
        model_config (ConfigDict): Pydantic configuration allowing the model to be
            immutable (frozen=True).

    Note:
        This is a value object representing a response from a language model
        that uses Retrieval-Augmented Generation, where external documents
        are retrieved to provide additional context for response generation.
    """
    model_config = ConfigDict(frozen=True)
    sources: List[DocumentRetrieval] = Field(default_factory=list)
